import type { NextPage } from 'next'
import Head from 'next/head'
import { Landing } from '../components/landing'
import { useStyles } from '../styles/home'

const Home: NextPage = () => {
   const { classes } = useStyles()

   return (
      <div className={classes.container}>
         <Head>
            <title>{`Home | Adopt a Minor Leaguer`}</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <Landing />
      </div>
   )
}

export default Home
